### ISSUE TITLE
Duplicate emailaddresses

### ISSUE THREAD

**Issue by Maskinisten** [ForumHulp/loginwithemail#1]
Hi, I cannot activate the login with email because there are duplicate entries.
(Duplicate emailaddresses in memberlist!)
It would be very cool if the ext also could show those entries! Because now I dont know how to solve this.

/Holger

**Comment by ForumHulp** [comment]
Hi Holger,
Install new version and click in ACP on emailaddresses (red) and it shows you the duplicates.
Good option BTW

**Comment by Maskinisten** [comment]
VERY nice!
