### ISSUE TITLE
Can't switch it on in phpbb 3.2.2

### ISSUE THREAD

**Issue by wcz-txp** [ForumHulp/loginwithemail#12]
Hello, after upgrading my board from 3.1.10 to 3.2.2 the extension stopped working. It is every time detecting duplicate email addresses, but when I manually use this sql request, then I get a zero result:

`SELECT username, user_email FROM phpbb_users list INNER JOIN (SELECT user_email_hash FROM phpbb_users WHERE user_type <> 2 GROUP BY user_email_hash HAVING count(user_email_hash) > 1) dup ON list.user_email_hash = dup.user_email_hash`

Clicking on the red link "emailadresses" gives me also a zero result.
![screenshot-2018-2-10 registrierung](https://user-images.githubusercontent.com/2091265/36061337-8669f17e-0e61-11e8-958f-00678abca41a.png)

"loginwithemail" is the last version from github, also as "forumhulp helper". 
phpbb 3.2.2 with php 7.0.27

I already tried to switch the email reuse on and off, but without success. Supposing, that there are really doubled email addresses, how can I find them?

**Comment by wcz-txp** [comment]
The only bad workaround I could figure out with my restricted programing knowledge, was to put a `			$not_allowed = false;
`
into the _allow_email_login_ function.

**Comment by Leinad4Mind** [comment]
I've tested on php 7.2.10 with 3.2.3 and its working good. But you need to clean the cache after installation. 

But that message saying email duplicated is the problem... I didnt had that problem.

I beleive you've users with the same user_email_hash, even when they dont have the same email. So try to update their email to something else and then send again the same one. It should fix the user_email_hash.

**Comment by wcz-txp** [comment]
In the meantime I switched to the more up to date 
**phpbb-ext-emaillogin**
https://github.com/marttiphpbb/phpbb-ext-emaillogin
https://www.phpbb.com/community/viewtopic.php?f=456&t=2474801

**Comment by Leinad4Mind** [comment]
Its not more "up to date" its just a smiliar ext that seems to do the same by different ways. But glad to know that "solved" your issue.
