### ISSUE TITLE
Not working on phpBB 3.2.7

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/loginwithemail#13]
Hi @ForumHulp,

I tested on a fresh install of phpBB 3.2.7 this extension doesn’t work?

Could you take a look, please?

Regards.

**Comment by luzpaz** [comment]
@Galixte what's the error ?

**Comment by Galixte** [comment]
@luzpaz I don’t talk about error message, only that the connexion doesn’t work when I try to log in with my e-mail adresse attached to my account.

**Comment by Galixte** [comment]
@ForumHulp Could you take a look, please?

**Comment by ForumHulp** [comment]
Tested on 3.2.8
