### ISSUE TITLE
Error with the extended lang-strings

### ISSUE THREAD

**Issue by Maskinisten** [ForumHulp/loginwithemail#2]
The Ext seems to extend the text Username with "/ email", but that does not work.
After activating the ext I only get "/ email" instead of "Username / email".

![-email](https://cloud.githubusercontent.com/assets/7782540/12815053/f4572278-cb43-11e5-8563-604405b67967.jpg)

**Comment by ForumHulp** [comment]
Problem of version 3.1, the extension is loaded before the language. 
Try again

**Comment by Maskinisten** [comment]
Nope, now "/ email" is not shown :-)

EDIT: WORKS!
Thanks!

**Comment by ForumHulp** [comment]
Version and link please
