### ISSUE TITLE
Bad serverlog entries Call to undefined function phpbb_validate_email()

### ISSUE THREAD

**Issue by Maskinisten** [ForumHulp/loginwithemail#3]
Hi, I have a lot of such entries in the serverlog:

[11-Feb-2016 08:57:13] WARNING: [pool _mydomain_.net] child 4444 said into stderr: "NOTICE: PHP message: PHP Fatal error: Call to undefined function forumhulp\loginwithemail\event\phpbb_validate_email() in /var/www/vhosts/_mydomain_.net/httpdocs/forum/ext/forumhulp/loginwithemail/event/listener.php on line 59

Had to deactivate the Ext.
What can I do about this?

**Comment by ForumHulp** [comment]
Hi Holger,

This function is a global function in phpbb and always available.
Which phpbb version and where does this happen in your site?

**Comment by Maskinisten** [comment]
Hi!
I have 3.1.7-PL1
What do you mean by "where"?

**Comment by ForumHulp** [comment]
Ok alse in 3.1.7PL1 it's a global function so it should be available always.
On what page is it generating your notice?

**Comment by Maskinisten** [comment]
Its from the serverlog, so I cannot see on which page it is generated
No errors in the http-log, so it seems to be handeled gracefully.

**Comment by ForumHulp** [comment]
Can you let me know when it happens again?

**Comment by Maskinisten** [comment]
It is in the logs almost all the time.
I had to deactivate the Ext because I feared it would affect registration or login.

**Comment by ForumHulp** [comment]
There are 3 different login screens and one registration screen. 
I can not reproduce this error.

**Comment by Maskinisten** [comment]
I will ask the serverguy to check the log again and then I will activate the Ext. Lets see if there is an indication based on what I do.

**Comment by Maskinisten** [comment]
Strange thing is that the Ext works as it should. I just activated it again and logged in with my emailaddress.

Will check the log later.

**Comment by ForumHulp** [comment]
If it can not find this function you are not able to login with your email

**Comment by wcz-txp** [comment]
I have the same error log, but looking through my access logs, this problem seems for me also linked to the tapatalk extension.
`/mobiquo/mobiquo.php HTTP/1.1" 503 490 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 Tapatalk/5.7.2"`
this is happened at the same time.
So maybe this is issue is a repeat of this one: https://github.com/ForumHulp/loginwithemail/issues/5

**Comment by ForumHulp** [comment]
OK it could be the same problem for Maskiisten

**Comment by wcz-txp** [comment]
definitively, he is also using the tapatalk extension ...
