### ISSUE TITLE
State of this plugin? 

### ISSUE THREAD

**Issue by habakuk007** [ForumHulp/loginwithemail#4]
Hi,

I have phpbb 3.1.8 and installed and enabled the extension, but could not get it to work...

When I try to login and try to use my email-address in the username field I get the message that the username is wrong.

Did I miss something?

Regards!
   Stefan

**Comment by ForumHulp** [comment]
Hi Stefan
Probably it couldn't change the file /phpbb/auth/provider/db.php
Look in your log file in maintenance tab

**Comment by habakuk007** [comment]
Hello, thanks for your reply.

I only have these Forumhulp entries in the admin log (and nothing in the error log): 

> administrator     188.174.197.217     Fr 18. Mär 2016, 21:19     Forumhulp Helper
> » Files succesfully changed  
> administrator     188.174.197.217     Fr 18. Mär 2016, 21:19     Erweiterung aktiviert
> » forumhulp/loginwithemail  
> administrator     188.174.197.217     Fr 18. Mär 2016, 21:18     Erweiterung aktiviert
> » forumhulp/helper

**Comment by ForumHulp** [comment]
Did you upgrade to 3.1.8 after the extension was enabled, then disabled it again, delete data and enable again.

**Comment by habakuk007** [comment]
I did the disabling and re-enabling, but still the same "username not known" error.

Any other idea?

**Comment by ForumHulp** [comment]
Is it showing Username / E-mail on the login screen?

**Comment by habakuk007** [comment]
It only shows "Benutzername" (Username).

**Comment by ForumHulp** [comment]
Can you find this :
global $phpbb_dispatcher; 
        $vars = array('sql', 'username_clean'); 
        extract($phpbb_dispatcher->trigger_event('forumhulp.loginwithemail.modify_sql', compact($vars))); 

in /phpbb/auth/provider/db.php

It should be there or you have to add it by hand

**Comment by habakuk007** [comment]
Yes, the code is in the file:

`global $phpbb_dispatcher;`
`$vars = array('sql', 'username_clean');`
`extract($phpbb_dispatcher->trigger_event('forumhulp.loginwithemail.modify_sql', compact($vars)));`

**Comment by ForumHulp** [comment]
Did you switch on in board configuration User registration settings Allow email login:

**Comment by habakuk007** [comment]
No, didn't know that I had to set this setting...

Thanks for your help!

**Comment by ForumHulp** [comment]
In all my extensions there is a message in the green box when enabling telling you where to look for settings or else things to know.

**Comment by habakuk007** [comment]
I didn't notice this box. I expected more information in the documentation (https://github.com/ForumHulp/loginwithemail/blob/master/README.md)

Regards! 
   Stefan
