### ISSUE TITLE
Incompatibility with tapatalk extension

### ISSUE THREAD

**Issue by wcz-txp** [ForumHulp/loginwithemail#5]
Hello,
this extension doesn't work together with installed tapatalk extension 3.1.7 (https://tapatalk.com/files/plugin/tapatalk_phpBB-3.1_v1.3.7.zip) in phpbb 3.1.8.

**Comment by ForumHulp** [comment]
That's correct, they don't have events in their scripts

**Comment by wcz-txp** [comment]
I informed them already. 

> Thank you for submitting your case.  We will review your case and do our best to get back to you in three business days.  
> Thanks-
> Tapatalk Support

**Comment by ForumHulp** [comment]
Ok wait for their andwer
