### ISSUE TITLE
Delete data from this extension

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/loginwithemail#8]
Hi @ForumHulp,

is this extension is compatible with phpBB 3.2.x ?

I ask you because when i have disabled this extension and after if i want to delete data from this extension i have this error message : “A module already have this name : UCP_IR”

( ! ) Fatal error: Call to a member function trigger_event() on null in C:\UwAmp_3.1.0\www\phpBB3\includes\acp\acp_extensions.php on line 75
Call Stack
#	Time	Memory	Function	Location
1	0.0006	150272	{main}( )	...\index.php:0
2	2.9911	13741952	p_master->load_active( )	...\index.php:82
3	2.9924	13845464	acp_extensions->main( )	...\functions_module.php:676

If i replace manually the files (in includes folder) those were modified by the extension with the original files from phpBB Vanilla, i have this error message : 

Catchable fatal error: Argument 1 passed to phpbb\db\migrator::get_callable_from_step() must be of the type array, null given, called in /phpBB3/phpbb/db/migrator.php on line 701 and defined in /phpBB3/phpbb/db/migrator.php on line 723

Information from Admin logs:

USERNAME	IP ADDRESS	DATE	ACTION	SELECT
Raphaël	::1	mar. juin 06, 2017 19:39	{LOG CORE DEINSTALLED}	
Raphaël	::1	mar. juin 06, 2017 19:39	Adds a module
» UCP_IR	
Raphaël	::1	mar. juin 06, 2017 19:38	Extension disabled
» forumhulp/helper	
Raphaël	::1	mar. juin 06, 2017 19:38	{LOG CORE NOT UPDATED}
/includes/acp/acp_extensions.php	
Raphaël	::1	mar. juin 06, 2017 19:38	Adds a module
» UCP_IR	
Raphaël	::1	mar. juin 06, 2017 19:38	Extension activation
» forumhulp/helper

I’m surprised, you don’t test installation/uninstallation when you develop an extension ? In my opinion it’s the basic test to prevent this kind of problem.

**Comment by ForumHulp** [comment]
The problem isn't in this extension but in the helper. 
The event is now in core so helper is updated.

**Comment by Galixte** [comment]
Thanks for informations !

But, the phpBB file : ```./phpbb/auth/provider/db.php``` is still overwritten by your extension, why ?

It adds this code:

```
		global $phpbb_dispatcher;
		$vars = array('sql', 'username_clean');
		extract($phpbb_dispatcher->trigger_event('forumhulp.loginwithemail.modify_sql', compact($vars)));

```
