### ISSUE TITLE
Recorvering password - email twice address asked, one from the login field and one from the correct email field

### ISSUE THREAD

**Issue by Galixte** [ForumHulp/loginwithemail#9]
Hi @ForumHulp,

on the recorvering password page usually the login and the email address are requested, but for the login field it’s displayed: « login / email » because the language key from this line: https://github.com/ForumHulp/loginwithemail/blob/master/language/en/info_acp_loginwithemail.php#L22 is displayed.
I think you should fix this problem.

Regards.

**Comment by ForumHulp** [comment]
Good finding Galixte.
It's solved, both methods are possible now

**Comment by MicMP3Man** [comment]
Hi, i've found this problem :-) Thank you 2 for links !
Maybe now it's better to just keep one area displayed, because now email only is necessary to have a new password.

**Comment by ForumHulp** [comment]
I was already thinking strange people want this but should be better this way

**Comment by Galixte** [comment]
Hi @MicMP3Man, did you try the last snapshot (1er juillet 16h17): https://github.com/ForumHulp/loginwithemail/archive/master.zip from @ForumHulp ? It’s ok for you ? :)

**Comment by MicMP3Man** [comment]
Hi @ForumHulp @Galixte , now when we enter username to recover password on my forum (http://www.forumtourangeau.org/ucp.php?mode=sendpassword) it doesn't operate. 
The recovry password only operate when we put email (so 2 times). 
Do you understand (sorry for my english ? Can U fix it @ForumHulp ? 
See U
